### ISSUE TITLE
Suggests assertTrue and assertFalse in preference to assertEqual

### ISSUE THREAD

**Issue by exarkun-insecure** [twisted/twistedchecker#43]
We prefer the more specific asserts, when relevant, so twistedchecker should suggest them.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-02-15T23:39:41Z
 * owner: tom.prince
 * the launchpad url was https://bugs.launchpad.net/bugs/1126746

**Comment by glyph** [comment]
`assertTrue` and `assertFalse` unfortunately only assert about _truthiness_, rather than actual equality to `True` and `False`.  I actually generally prefer `assertEqual` because it is a more specific test, less flexible, and is more likely to report spuriously passing truthiness values.  If anyone would like to discuss further they may certainly reopen, but I think there's plenty to do on twistedchecker in the meanwhile :).

**Comment by adiroiban** [comment]
For my project I have introduced custom assertions assertIsTrue and assertIsFalse as nicer names for `assertIs`.

`self.assertEqual(True, 1)` will still pass ... but yes, `self.assertEqual(True, 'sa')` will fail

so I would say that instead of `assertEqual` we should use `assertIs`

**Comment by glyph** [comment]
@adiroiban - the identity-ness of `True` and `False` always struck me as an implementation detail; in the same way that you shouldn't `assertIs(4, ...)` it seemed to me that you shouldn't `assertIs(True, ...)` even though both of those will technically work all the time on present implementations of Python.
